### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by dwoodev** [Th-Underscore/boogaPlus#1]
09:33:05-399306 INFO     Loading the extension "boogaPlus"
09:33:05-411308 ERROR    Could not import the requirements for 'boogaPlus'. Make
                         sure to install the requirements for the extension.

                         * To install requirements for all available extensions,
                         launch the
                           update_wizard script for your OS and choose the B
                         option.

                         * To install the requirements for this extension alone,
                         launch the
                           cmd script for your OS and paste the following
                         command in the
                           terminal window that appears:

                         Linux / Mac:

                         pip install -r extensions/boogaPlus/requirements.txt
                         --upgrade

                         Windows:

                         pip install -r extensions\boogaPlus\requirements.txt
                         --upgrade

09:33:05-413308 ERROR    Failed to load the extension "boogaPlus".
Traceback (most recent call last):
  File "C:\Users\dwoo\Desktop\localllama\oobafix\text-generation-webui-main\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dwoo\Desktop\localllama\oobafix\text-generation-webui-main\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\dwoo\Desktop\localllama\oobafix\text-generation-webui-main\extensions\boogaPlus\script.py", line 12, in <module>
    import extensions.boogaplus.utils.cache as cache
ModuleNotFoundError: No module named 'extensions.boogaplus'

Wanted to try it out but getting this error at launch time. There doesn't appear to be a requirements.txt so I can't apple the fix option.

what am I missing here?

Thanks!

**Comment by Th-Underscore** [comment]
Rename the folder to "boogaplus" lowercase. Gonna fix that in my next commit.
